services:
  # Should only be ran during initial bootstrapping of nodes with setup.sh
  mavkit-snapshot-import:
    container_name: mavkit-snapshot-import
    image: mavrykdynamics/mavryk:mavkit-v20.3-rc2
    entrypoint: /bin/sh
    command: -c "mavkit-node config init --network https://testnets.mavryk.network/atlasnet -d /var/run/mavryk/node/data --config-file /var/run/mavryk/node/config.json && mavkit-node snapshot import /atlasnet.snapshot -d /var/run/mavryk/node/data --config-file /var/run/mavryk/node/config.json"
    volumes:
      - ./atlasnet.snapshot:/atlasnet.snapshot
      - node_data:/var/run/mavryk/node
      - client_data:/var/run/mavryk/client
    environment:
      PROTOCOL: PtBoreas

  mavkit-node:
    container_name: mavkit-node
    image: mavrykdynamics/mavryk:mavkit-v20.3-rc2
    entrypoint: /bin/sh
    command: -c "mavkit-node run --rpc-addr 0.0.0.0:8732 --allow-all-rpc 0.0.0.0:8732 --history-mode full -d /var/run/mavryk/node/data --config-file /var/run/mavryk/node/config.json"
    ports:
      - 9732:9732
      - 127.0.0.1:8732:8732
    environment:
      NODE_HOST: mavkit-node
      PROTOCOL: PtBoreas
      MAVRYK_CLIENT_DIR: /var/run/mavryk/client
    volumes:
      - node_data:/var/run/mavryk/node
      - client_data:/var/run/mavryk/client
    restart: on-failure

  mavkit-baker:
    container_name: mavkit-baker
    image: mavrykdynamics/mavryk:mavkit-v20.3-rc2
    hostname: mavkit-baker
    command: mavkit-baker --liquidity-baking-toggle-vote pass --adaptive-issuance-vote on $BAKER_ALIAS
    environment:
      NODE_HOST: mavkit-node
      PROTOCOL: PtBoreas
      MAVRYK_CLIENT_DIR: /var/run/mavryk/client
      BAKER_ALIAS: ${BAKER_ALIAS}
    volumes:
      - client_data:/var/run/mavryk/client
      - node_data:/var/run/mavryk/node
    restart: on-failure

  mavkit-accuser:
    container_name: mavkit-accuser
    image: mavrykdynamics/mavryk:mavkit-v20.3-rc2
    hostname: mavkit-accuser
    command: mavkit-accuser
    environment:
      NODE_HOST: mavkit-node
      PROTOCOL: PtBoreas
    volumes:
      - client_data:/var/run/mavryk/client
      - node_data:/var/run/mavryk/node
    restart: on-failure

volumes:
  node_data: {}
  client_data: {}